server:
  port: 8088

---


keycloak-client:
  server-url: https://9090-uengineysw-carrent-wjzq45ynvz2.ws-us67.gitpod.io
  realm: master

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: carRental
          uri: http://localhost:8081
          predicates:
            - Path=/carRentSystems/** 
        - id: carManagement
          uri: http://localhost:8082
          predicates:
            - Path=/vehicleManagementSystems/** 
        - id: view
          uri: http://localhost:8083
          predicates:
            - Path= /totalCarLists/**
        - id: userManagement
          uri: http://localhost:8084
          predicates:
            - Path=/memberManagementSystems/** 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: https://9090-uengineysw-carrent-wjzq45ynvz2.ws-us67.gitpod.io/realms/${keycloak-client.realm}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: master
            client-secret: 
            redirect-uri: https://8088-uengineysw-carrent-wjzq45ynvz2.ws-us67.gitpod.io/login/oauth2/code/master
            authorization-grant-type: authorization_code
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs

---

spring:
  profiles: docker
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: "<client-id>"
            client-secret: 
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            authorization-grant-type: authorization_code
            scope: openid
      resourceserver:
        jwt:
          jwk-set-uri: ${keycloak-client.server-url}/realms/${keycloak-client.realm}/protocol/openid-connect/certs
  cloud:
    gateway:
      routes:
        - id: carRental
          uri: http://carRental:8080
          predicates:
            - Path=/carRentSystems/** 
        - id: carManagement
          uri: http://carManagement:8080
          predicates:
            - Path=/vehicleManagementSystems/** 
        - id: view
          uri: http://view:8080
          predicates:
            - Path= /totalCarLists/**
        - id: userManagement
          uri: http://userManagement:8080
          predicates:
            - Path=/memberManagementSystems/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080