---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: carRental
  labels:
    app: carRental
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carRental
  template:
    metadata:
      labels:
        app: carRental
    spec:
      containers:
        - name: carRental
          image: username/carRental:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: carManagement
  labels:
    app: carManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carManagement
  template:
    metadata:
      labels:
        app: carManagement
    spec:
      containers:
        - name: carManagement
          image: username/carManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: view
  labels:
    app: view
spec:
  replicas: 1
  selector:
    matchLabels:
      app: view
  template:
    metadata:
      labels:
        app: view
    spec:
      containers:
        - name: view
          image: username/view:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: userManagement
  labels:
    app: userManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userManagement
  template:
    metadata:
      labels:
        app: userManagement
    spec:
      containers:
        - name: userManagement
          image: username/userManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: carRental
  labels:
    app: carRental
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: carRental


---


apiVersion: v1
kind: Service
metadata:
  name: carManagement
  labels:
    app: carManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: carManagement


---


apiVersion: v1
kind: Service
metadata:
  name: view
  labels:
    app: view
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: view


---


apiVersion: v1
kind: Service
metadata:
  name: userManagement
  labels:
    app: userManagement
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: userManagement

